# port
server:
  port: 8079
# DataSource配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_work?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
# security token timeout(mins)
token:
  timeout:
    jwt: 1
    refresh: 3
    